name: CI on macOS

on: [push]

jobs:
  build_ocaml:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: install ocaml
      run: |
        which git
        [ -f /usr/local/bin/git ] || ln -s `which git` /usr/local/bin/git
        bash -ex .travis-ocaml.sh
        eval $(opam env)
      env:
        OPAM_VERSION: 2
        OCAML_VERSION: 4.13
        TRAVIS_OS_NAME: osx
